# PHASE 1 - Step 3: Data Inspection and Cleaning Strategy

In [6]:
import pandas as pd

# Loading the dataset
results = pd.read_csv('../data/raw/results.csv')
print("Results from results.csv:")
print(results.head())

rankings = pd.read_csv('../data/raw/fifa_ranking-2024-06-20.csv')
print("\n")  # Adding a newline for better readability
print("Results from fifa_ranking-2024-06-20.csv:")
print(rankings.head())

Results from results.csv:
         date home_team away_team  home_score  away_score tournament     city  \
0  1872-11-30  Scotland   England           0           0   Friendly  Glasgow
1  1873-03-08   England  Scotland           4           2   Friendly   London
2  1874-03-07  Scotland   England           2           1   Friendly  Glasgow
3  1875-03-06   England  Scotland           2           2   Friendly   London
4  1876-03-04  Scotland   England           3           0   Friendly  Glasgow

    country  neutral
0  Scotland    False
1   England    False
2  Scotland    False
3   England    False
4  Scotland    False


Results from fifa_ranking-2024-06-20.csv:
    rank       country_full country_abrv  total_points  previous_points  \
0  140.0  Brunei Darussalam          BRU           2.0              0.0
1   33.0           Portugal          POR          38.0              0.0
2   32.0             Zambia          ZAM          38.0              0.0
3   31.0             Greece          GRE          38.0              0.0
4   30.0            Algeria          ALG          39.0              0.0

   rank_change confederation   rank_date
0          140           AFC  1992-12-31
1           33          UEFA  1992-12-31
2           32           CAF  1992-12-31
3           31          UEFA  1992-12-31
4           30           CAF  1992-12-31

In [8]:
# setting the display options to show all columns and rows
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 2000)

In [12]:
# Displaying the info from the datasets to understand their structure
results.info()
print("\n")  # Adding a newline for better readability
print(rankings.dtypes)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 49071 entries, 0 to 49070
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        49071 non-null  object
 1   home_team   49071 non-null  object
 2   away_team   49071 non-null  object
 3   home_score  49071 non-null  int64
 4   away_score  49071 non-null  int64
 5   tournament  49071 non-null  object
 6   city        49071 non-null  object
 7   country     49071 non-null  object
 8   neutral     49071 non-null  bool
dtypes: bool(1), int64(2), object(6)
memory usage: 3.0+ MB


rank               float64
country_full        object
country_abrv        object
total_points       float64
previous_points    float64
rank_change          int64
confederation       object
rank_date           object
dtype: object

In [16]:
# Cleaning Column names
rankings = rankings.rename(columns={
    'country_full' : 'team',
    'rank_date' : 'date',
    'rank':'ranking',
    'total_points':'points'
})

rankings.columns

Index(['ranking', 'team', 'country_abrv', 'points', 'previous_points',
       'rank_change', 'confederation', 'date'],
      dtype='object')

In [19]:
print(results['date'].head())
print()
print(rankings['date'].head())

0    1872-11-30
1    1873-03-08
2    1874-03-07
3    1875-03-06
4    1876-03-04
Name: date, dtype: object

0    1992-12-31
1    1992-12-31
2    1992-12-31
3    1992-12-31
4    1992-12-31
Name: date, dtype: object

In [22]:
# Converting Dates to datetime format
results['date'] = pd.to_datetime(results['date'])
rankings['date'] = pd.to_datetime(rankings['date'])

print(results.dtypes)
print()
print(rankings.dtypes)

date          datetime64[ns]
home_team             object
away_team             object
home_score             int64
away_score             int64
tournament            object
city                  object
country               object
neutral                 bool
dtype: object

ranking                   float64
team                       object
country_abrv               object
points                    float64
previous_points           float64
rank_change                 int64
confederation              object
date               datetime64[ns]
dtype: object

In [23]:
# Filter the matches that are from 1993 and onwards
results = results[results['date'] >= '1993-01-01']

results.head()

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral
18704,1993-01-01,Ghana,Mali,1,1,Friendly,Libreville,Gabon,True
18705,1993-01-02,Gabon,Burkina Faso,1,1,Friendly,Libreville,Gabon,False
18706,1993-01-02,Kuwait,Lebanon,2,0,Friendly,Kuwait City,Kuwait,False
18707,1993-01-03,Burkina Faso,Mali,1,0,Friendly,Libreville,Gabon,True
18708,1993-01-03,Gabon,Ghana,2,3,Friendly,Libreville,Gabon,False

In [26]:
# Inspecting the unique teams in both datasets
results_teams = set(results['home_team'].unique())
rankings_teams = set(rankings['team'].unique())

# Finding teams that are in results but not in rankings
missing_in_rankings = results_teams - rankings_teams
print("Teams in results but not in rankings:")
print(missing_in_rankings)
print(f'There are {len(missing_in_rankings)} teams in results that are not in rankings.')

Teams in results but not in rankings:
{'Donetsk PR', 'Provence', 'Hitra', 'United States Virgin Islands', 'Northern Mariana Islands', 'Saint Kitts and Nevis', 'Gotland', 'Gambia', 'Tuvalu', 'Kárpátalja', 'South Ossetia', 'Shetland', 'Mayotte', 'Orkney', 'Réunion', 'United States', 'Chameria', 'Chechnya', 'Ynys Môn', 'Rhodes', 'Kabylia', 'Catalonia', 'Kernow', 'Madrid', 'Raetia', 'Western Sahara', 'Saint Martin', 'Ellan Vannin', 'Isle of Wight', 'Seborga', 'Cape Verde', 'Tamil Eelam', 'Ivory Coast', 'Saint Helena', 'Marshall Islands', 'Sealand', 'Frøya', 'Falkland Islands', 'Saare County', 'Aymara', 'Găgăuzia', 'Corsica', 'Délvidék', 'Bonaire', 'Sápmi', 'Menorca', 'Sark', 'Taiwan', 'Guadeloupe', 'Felvidék', 'Western Armenia', 'Andalusia', 'Czech Republic', 'Brittany', 'Ryūkyū', 'Canary Islands', 'Romani people', 'Franconia', 'Republic of St. Pauli', 'United Koreans in Japan', 'Sint Maarten', 'Kiribati', 'Biafra', 'Palau', 'Monaco', 'Matabeleland', 'Abkhazia', 'Micronesia', 'Vatican City', 'Elba Island', 'Saint Pierre and Miquelon', 'Barawa', 'Saint Barthélemy', 'North Korea', 'Parishes of Jersey', 'Luhansk PR', 'Padania', 'Martinique', 'Åland Islands', 'Occitania', 'Saint Vincent and the Grenadines', 'Artsakh', 'Darfur', 'Kyrgyzstan', 'Zanzibar', 'Guernsey', 'Isle of Man', 'Curaçao', 'Hmong', 'Silesia', 'Western Isles', 'Yoruba Nation', 'Jersey', 'Somaliland', 'Székely Land', 'French Guiana', 'Mapuche', 'County of Nice', 'Brunei', 'Chagos Islands', 'Saugeais', 'Ticino', 'Saint Lucia', 'South Korea', 'Iran', 'DR Congo', 'Alderney', 'Arameans Suryoye', 'Yorkshire', 'Cascadia', 'Panjab', 'Iraqi Kurdistan', 'Tibet', 'São Tomé and Príncipe', 'Northern Cyprus', 'West Papua', 'Greenland', 'Gozo', 'Basque Country', 'Galicia'}
There are 120 teams in results that are not in rankings.

## The Results dataset includes somes teams that are not considered FIFA teams.
This means that we need to filter. 
- We want to keep only the matches that BOTH teams exists in FIFA Rankings
- Remove all the Non-FIFA teams
- Then fix any mismatches

In [28]:
# Identifying the Valid FIFA teams
ranking_teams = set(rankings['team'].unique())

# Filtering teams from the results
results = results[
    (results['home_team'].isin(ranking_teams)) &
    (results['away_team'].isin(ranking_teams))
]

# Checking again for the unique teams
# Inspecting the unique teams in both datasets
results_teams = set(results['home_team'].unique())
rankings_teams = set(rankings['team'].unique())

# Finding teams that are in results but not in rankings
missing_in_rankings = results_teams - rankings_teams
print("Teams in results but not in rankings:")
print(missing_in_rankings)
print(f'There are {len(missing_in_rankings)} teams in results that are not in rankings.')

Teams in results but not in rankings:
set()
There are 0 teams in results that are not in rankings.

# PHASE 1 - Step 4: Merge Rankings into Match Data

We cannot use a normal merge since the rankings change over time. 
- For each macth, we need the most recent ranking BEFORE the match date

In [29]:
# Sorting both datasets by date
results = results.sort_values("date")
rankings = rankings.sort_values("date")

# checking the first few rows of the sorted datasets
print(results.head())
print("\n")
print(rankings.head())

            date     home_team     away_team  home_score  away_score  \
18704 1993-01-01         Ghana          Mali           1           1
18705 1993-01-02         Gabon  Burkina Faso           1           1
18706 1993-01-02        Kuwait       Lebanon           2           0
18707 1993-01-03  Burkina Faso          Mali           1           0
18708 1993-01-03         Gabon         Ghana           2           3

      tournament         city country  neutral
18704   Friendly   Libreville   Gabon     True
18705   Friendly   Libreville   Gabon    False
18706   Friendly  Kuwait City  Kuwait    False
18707   Friendly   Libreville   Gabon     True
18708   Friendly   Libreville   Gabon    False


     ranking               team country_abrv  points  previous_points  \
0      140.0  Brunei Darussalam          BRU     2.0              0.0
105    136.0    Solomon Islands          SOL     2.0              0.0
106    135.0         Cabo Verde          CPV     3.0              0.0
107    134.0         Mauritania          MTN     3.0              0.0
108    133.0         Bangladesh          BAN     3.0              0.0

     rank_change confederation       date
0            140           AFC 1992-12-31
105          136           OFC 1992-12-31
106          135           CAF 1992-12-31
107          134           CAF 1992-12-31
108          133           AFC 1992-12-31

In [30]:
# Merging the home team rankings
home_rankings = rankings.rename(columns={
    'team': 'home_team',
    'ranking': 'home_ranking',
    'points': 'home_points'
})

results = pd.merge_asof(
    results,
    home_rankings,
    by='home_team',
    left_on='date',
    right_on='date',
    direction='backward'
)

# Merging the away team rankings
away_rankings = rankings.rename(columns={
    'team': 'away_team',
    'ranking': 'away_ranking',
    'points': 'away_points'
})

results = pd.merge_asof(
    results,
    away_rankings,
    by='away_team',
    left_on='date',
    right_on='date',
    direction='backward'
)

results.head()

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral,home_ranking,country_abrv_x,home_points,previous_points_x,rank_change_x,confederation_x,away_ranking,country_abrv_y,away_points,previous_points_y,rank_change_y,confederation_y
0,1993-01-01,Ghana,Mali,1,1,Friendly,Libreville,Gabon,True,39.0,GHA,34.0,0.0,39.0,CAF,69.0,MLI,22.0,0.0,69.0,CAF
1,1993-01-02,Gabon,Burkina Faso,1,1,Friendly,Libreville,Gabon,False,55.0,GAB,27.0,0.0,55.0,CAF,97.0,BFA,11.0,0.0,97.0,CAF
2,1993-01-02,Kuwait,Lebanon,2,0,Friendly,Kuwait City,Kuwait,False,71.0,KUW,21.0,0.0,71.0,AFC,161.0,LBN,0.0,0.0,161.0,AFC
3,1993-01-03,Burkina Faso,Mali,1,0,Friendly,Libreville,Gabon,True,97.0,BFA,11.0,0.0,97.0,CAF,69.0,MLI,22.0,0.0,69.0,CAF
4,1993-01-03,Gabon,Ghana,2,3,Friendly,Libreville,Gabon,False,55.0,GAB,27.0,0.0,55.0,CAF,39.0,GHA,34.0,0.0,39.0,CAF

In [31]:
# checking for Nans
results[['home_ranking','away_ranking']].isna().sum()

home_ranking    142
away_ranking    236
dtype: int64

In [35]:
# checking percentage of Nans
print("Total matches:", len(results))
print("Home ranking NaN %:", results['home_ranking'].isna().mean() * 100)
print("Away ranking NaN %:", results['away_ranking'].isna().mean() * 100)

Total matches: 24535
Home ranking NaN %: 0.578765029549623
Away ranking NaN %: 0.9618911758712043

### Since the percentages of NaNs values are very low compared with the data, We are going to drop them. We would be losing less than 1% of the data.

In [37]:
# Dropping the NaNs values
results = results.dropna(subset=['home_ranking', 'away_ranking'])

# Verifying the are dropped
print("Total matches:", len(results))
print(results[['home_ranking', 'away_ranking']].isna().sum())

Total matches: 24184
home_ranking    0
away_ranking    0
dtype: int64

# What we have now: 
- A time-conistent dataset where every match has: 
    - Match date
    - Home team
    - Away team
    - Goals
    - Tournament
    - Neutral flag
    - Home ranking at that time
    - Away ranking at that time
    - Home ranking points
    - Away ranking points

In [39]:
# Saving the cleaned results into a new CSV file
results.to_csv('../data/processed/results_cleaned.csv', index=False)

# Checking if the file is saved correctly
cleaned_results = pd.read_csv('../data/processed/results_cleaned.csv')
print(cleaned_results.head())
print(cleaned_results.shape)

         date     home_team     away_team  home_score  away_score tournament  \
0  1993-01-01         Ghana          Mali           1           1   Friendly
1  1993-01-02         Gabon  Burkina Faso           1           1   Friendly
2  1993-01-02        Kuwait       Lebanon           2           0   Friendly
3  1993-01-03  Burkina Faso          Mali           1           0   Friendly
4  1993-01-03         Gabon         Ghana           2           3   Friendly

          city country  neutral  home_ranking country_abrv_x  home_points  \
0   Libreville   Gabon     True          39.0            GHA         34.0
1   Libreville   Gabon    False          55.0            GAB         27.0
2  Kuwait City  Kuwait    False          71.0            KUW         21.0
3   Libreville   Gabon     True          97.0            BFA         11.0
4   Libreville   Gabon    False          55.0            GAB         27.0

   previous_points_x  rank_change_x confederation_x  away_ranking  \
0                0.0           39.0             CAF          69.0
1                0.0           55.0             CAF          97.0
2                0.0           71.0             AFC         161.0
3                0.0           97.0             CAF          69.0
4                0.0           55.0             CAF          39.0

  country_abrv_y  away_points  previous_points_y  rank_change_y  \
0            MLI         22.0                0.0           69.0
1            BFA         11.0                0.0           97.0
2            LBN          0.0                0.0          161.0
3            MLI         22.0                0.0           69.0
4            GHA         34.0                0.0           39.0

  confederation_y
0             CAF
1             CAF
2             AFC
3             CAF
4             CAF
(24184, 21)